<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-18 14:42
=======
# Generated by Django 4.0.2 on 2022-02-17 06:50
>>>>>>> dfdc1497525530c4576a0f9febb8a26f44ebfcef

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(max_length=100000),
        ),
    ]
