# Generated by Django 4.0.2 on 2022-02-21 16:38

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True),
        ),
    ]
